# Iniciar app local
up:
	@echo "🚀 Iniciando a aplicação local com Flask..."
	python3 run.py

# Gerar imagem e subir com Docker + Nginx
deploy:
	@echo "🐳 Gerando imagem Docker e subindo com Nginx..."
	docker compose -f docker-compose.yml up --build -d

# Dropar e recriar banco
reboot_db:
	@echo "🗑️ Dropar banco de dados..."
	python3 db_manage.py dropar
	@echo "✅ Recriando banco de dados..."
	python3 db_manage.py criar

# Ver logs da app Flask
logs:
	@echo "📋 Exibindo logs do container Flask..."
	docker compose logs -f web
